name: Cypress Cloud

on:  
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses:  actions/checkout@v3.5.3
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.7.2
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 71fa780c-d062-43bf-b4d7-a35611445523
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
